version: '3'

networks:
    bibbox-default-network:
      external: true
services:

  bibbox-sys-commander-apacheproxy:
    container_name: bibbox-sys-commander-apacheproxy
    restart: unless-stopped
    networks:
    - bibbox-default-network
    build:
      context:    ./apacheproxy
      dockerfile: Dockerfile
    volumes:
      - /opt/bibbox/proxy/sites:/usr/local/apache2/conf/sites
      - /opt/bibbox/proxy/letsencrypt:etc/letsencrypt
      - /opt/bibbox/sys-bibbox/frontend/dist/sys-bibbox-client:/var/www/html/sys-bibbox-client
    ports:
      - "80:80"
      - "443:443"
    environment:
      - DOMAINNAME=${DOMAINNAME:-demo.bibbox.org}
      - EMAIL=${EMAIL:-backoffice.bibbox@gmail.com}
    hostname: ${DOMAINNAME:-demo.bibbox.org}

#  bibbox-sys-commander-nginx:
#    container_name: bibbox-sys-commander-nginx
#    restart: unless-stopped
#    networks:
#    - bibbox-default-network
#    image: nginx
#    links:
#        -  bibbox-sys-commander-backend:backend
#    build:
#      context:    ./nginx
#      dockerfile: Dockerfile
#    volumes:
#      - ./client/dist:/usr/share/nginx/html
#      - ./proxy-configs/nginx.conf:/etc/nginx/nginx.conf
#      - /opt/bibbox:/opt/bibbox
#    ports:
#      - "8080:80"
#    depends_on:
#      -  bibbox-sys-commander-backend


  bibbox-sys-commander-backend:
    container_name: bibbox-sys-commander-backend
    restart: unless-stopped
    networks:
    - bibbox-default-network
    links:
        -  bibbox-sys-commander-redis:redis
        -  bibbox-sys-commander-celery:celery
        -  bibbox-sys-commander-postgres:postgres
    build:
      context:    ./backend
      dockerfile: Dockerfile
    ports:
        - "5010:5000"  
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/bibbox:/opt/bibbox
      - ./backend:/usr/src/bibbox-sys-commander/backend
    env_file:
      - .env

  bibbox-sys-commander-celery:
    container_name:  bibbox-sys-commander-celery
    restart: unless-stopped
    networks:
    - bibbox-default-network
    links:
        -  bibbox-sys-commander-redis:redis
        -  bibbox-sys-commander-postgres:postgres
    build:
      context:    ./backend
      dockerfile: Dockerfile
    command: "celery worker  -A celery_worker.app_celerey --loglevel=info"
    volumes:
      - ./data/celery:/queue
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/bibbox:/opt/bibbox
      - ./backend:/usr/src/bibbox-sys-commander/backend
    env_file:
       - .env

  bibbox-sys-commander-celery-monitor:
    container_name: bibbox-sys-commander-celery-monitor
    build:
      context:    ./backend
      dockerfile: Dockerfile
    networks:
    - bibbox-default-network
    links:
        -  bibbox-sys-commander-redis:redis
    restart: unless-stopped
    ports:
        - "5011:5555"    
    entrypoint: flower
    command:  -celery A celery_worker.app_celerey --port=5555 --broker=redis://redis:6379/0 
    depends_on:
      - bibbox-sys-commander-redis
    volumes:
      - ./data/celery:/queue
      - ./backend:/usr/src/bibbox-sys-commander/backend
      - /opt/bibbox:/opt/bibbox

  bibbox-sys-commander-postgres:
      container_name:  bibbox-sys-commander-postgres
      restart: unless-stopped
      networks:
       - bibbox-default-network
      build:
        context:   ./postgresql
        dockerfile: Dockerfile
      ports:
        - "5432:5432" 
      volumes:
        - ./data/postgresql/data:/var/lib/postgresql/data
      env_file:
        - .env

  bibbox-sys-commander-redis:
      container_name: bibbox-sys-commander-redis
      image: redis
      networks:
        - bibbox-default-network
      restart: unless-stopped
      ports:
        - "6379:6379" 
      volumes:
        - ./data/redis/data:/data
      env_file:
        - .env


  bibbox-sys-commander-adminer:
      container_name:  bibbox-sys-commander-adminer
      networks:
      - bibbox-default-network
      image: adminer
      restart: unless-stopped
      links:
        - bibbox-sys-commander-postgres:postgres
      ports:
        - "5012:8080" 
      environment:
        ADMINER_DEFAULT_DB_DRIVER: pgsql
        ADMINER_DEFAULT_DB_HOST: postgres
        ADMINER_DEFAULT_DB_NAME: bibbox
  
  bibbox-sys-commander-cadvisor:      
      container_name: bibbox-sys-commander-cadvisor
      image: gcr.io/cadvisor/cadvisor
      networks:
      - bibbox-default-network
      restart: unless-stopped
      ports:
        - "5013:8080"  
      volumes:
        - /:/rootfs:ro 
        - /var/run:/var/run:ro 
        - /sys:/sys:ro 
        - /var/lib/docker/:/var/lib/docker:ro 
        - /var/run/docker.sock:/var/run/docker.sock:ro 
        - /dev/disk/:/dev/disk:ro 
  